<?php
/**
 * Created by PhpStorm.
 * User: darevski
 * Date: 12.04.16
 * Time: 16:46
 */

namespace Application\Units;


class PDF_Generator extends \TCPDF{

    public function Header()
    {
        


        //$this->SetFont('roboto','',4);
        //$this->writeHTMLCell(0,0,'','',$header);
        parent::Header(); // TODO: Change the autogenerated stub
    }

    public function Footer()
    {
     //   parent::Footer(); // TODO: Change the autogenerated stub
    }

    public function setHeaderData($ln = '', $lw = 0, $ht = '', $hs = '', $tc = array(0, 0, 0), $lc = array(0, 0, 0))
    {
        parent::setHeaderData($ln, $lw, $ht, $hs, $tc, $lc); // TODO: Change the autogenerated stub
    }
    public function setFooterData($tc = array(0, 0, 0), $lc = array(0, 0, 0))
    {
        parent::setFooterData($tc, $lc); // TODO: Change the autogenerated stub
    }
}